if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("tximport")
BiocManager::install("DESeq2")

install.packages(c('pheatmap','mclust','reshape2','ggplot2','readr'))


library(DESeq2)
library(tximport)
library(ggplot2)
#Delete everithing in your R environment
rm(list=ls())

#Set your working directory. This should be the directoy containing all the Salmon results, remember you should have 16 folders with salmon results
wd<-"/data/diriano/cen5789_salmon/"
setwd(wd)

#Loading the experimental design
#we use the R read.delim to load a text file, that has columns separated by TABs, this is stores inside R as an object called target, a data.frame
targets<-read.delim("targets.txt",header=T)
rownames(targets)<-targets$SampleName
targets$Genotype<-as.factor(targets$Genotype)
targets$EnvironmentalStress<-as.factor(targets$EnvironmentalStress)

#Preparing to load the salmon quantification
#We need to prepare and object that has the sample names, and the location on disk of the quant.sf files produced by salmon
#We have the samples names in the target object, in the SampleName column,
# and we know that in our working directoy we have a folder for each sample,
# with the same name as the SampleName and the quat.sf file is inside that directory

myFiles<-paste(wd, targets$SampleName,"/quant.sf",sep="")

#Check whether these paths look ok
myFiles
#Add the sample name as the name of each path
names(myFiles)<-targets$SampleName
myFiles

#Check whether these paths actually exists on disk
all(file.exists(myFiles))

#Now, let load the mapping of transcript to gene identifiers
tx2gene<-read.delim("tx2gene.txt",header=F)
head(tx2gene)

#Let's see one example of a gene that has 3 transcripts
tx2gene[which(tx2gene$V2=='AT1G51370'),]

#Now, let's import the salmon quantification data into R, for this we will use the package tximport
txi.salmon<-tximport(files = myFiles, type = 'salmon', tx2gene = tx2gene, txIn = TRUE, txOut = FALSE)

#Just in order to compare between the quantification at the level of gene and transcript we will load the data at the level of transcripts
txi.salmon.tx<-tximport(files = myFiles, type = 'salmon', tx2gene = tx2gene, txIn = TRUE, txOut = TRUE)
head(txi.salmon$counts['AT1G51370',])
head(txi.salmon.tx$counts[c('AT1G51370.1','AT1G51370.2','AT1G51370.3'),])
#Let's just remove the quantification at the level of transcrip, as we will not use it
rm(txi.salmon.tx)

seqEffort<-as.data.frame(colSums(txi.salmon$counts))
seqEffort$Samples<-rownames(seqEffort)
colnames(seqEffort)<-c('NumberFragments', 'Samples')
#Let's compare the sequencing effort for all samples
p<- ggplot(seqEffort, aes(x=Samples,y=NumberFragments))+ 
  geom_col()

# Let's try to improve the figure, remove the background and put the sample names at an angle
p + theme_bw() +
  theme(axis.text.x = element_text(angle=60, size = 12, hjust = 1))
# Let's change the axis names
p + theme_bw() +
  theme(axis.text.x = element_text(angle=60, size = 12, hjust = 1)) +
  xlab("Amostras") +
  ylab("Número de fragmentos sequenciados")

#We will carry out the identification of DEG using the package DESeq2, so let's import our raw counts into DESeq2
targets$Number<-NULL
targets$SampleName<-NULL
dds <- DESeqDataSetFromTximport(txi.salmon, colData = targets, design = ~Genotype + EnvironmentalStress)

#Define the base level condition for the experimental factors under study
dds$Genotype <-relevel(dds$Genotype, ref='WT')
dds$EnvironmentalStress <-relevel(dds$EnvironmentalStress, ref='None')

# Let's have a loot at the object generated by DESeq2
head(dds)

